//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurant.BaseDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Check_All
    {
        public int id { get; set; }
        public int Id_Checks { get; set; }
        public string Name_food { get; set; }
        public decimal Prise { get; set; }
    
        public virtual Checks Checks { get; set; }
    }
}
