//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurant.BaseDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu
    {
        public int Id { get; set; }
        public int id_Position { get; set; }
        public string Name_food { get; set; }
        public string Descriptions { get; set; }
        public decimal Prise { get; set; }
        public string Img { get; set; }
    
        public virtual Position Position { get; set; }
    }
}
